### ISSUE TITLE
One error occurred after adding dynamic-cdn-webpack-plugin

### ISSUE THREAD

**Issue by qmiao128** [mastilver/dynamic-cdn-webpack-plugin#43]
The following is outputing logs.
=========================================================
node_modules/dynamic-cdn-webpack-plugin/lib/index.js:105
        compiler.hooks.normalModuleFactory.tap(pluginName, nmf => {
                       ^

TypeError: Cannot read property 'normalModuleFactory' of undefined

**Comment by aulisius** [comment]
Are you using `webpack <= 3` ? Use `v3.4.1` for compatability with `webpack@3`

**Comment by sinanerdem** [comment]
I am receiving the same error.

$ npm view webpack version
4.16.3

I use the latest version of cdn-webpack-plugin

**Comment by aulisius** [comment]
Hey @sinanerdem, can you also post the exact version of dynamic-cdn-webpack-plugin and the entire error logs? We can then determine if this issue needs to reopened or we can tackle it in a new issue.

**Comment by sinanerdem** [comment]
Thank you.

webpack-cdn-plugin 2.2.0

Here is the error:
TypeError: Cannot read property 'normalModuleFactory' of undefined
    at DynamicCdnWebpackPlugin.execute (/Users/sinan/Documents/code/vue_projects/sinan/node_modules/dynamic-cdn-webpack-plugin/lib/index.js:105:24)
    at DynamicCdnWebpackPlugin.apply (/Users/sinan/Documents/code/vue_projects/sinan/node_modules/dynamic-cdn-webpack-plugin/lib/index.js:90:18)
    at Compiler.apply (/Users/sinan/Documents/code/vue_projects/sinan/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/sinan/Documents/code/vue_projects/sinan/node_modules/webpack/lib/webpack.js:33:19)
    at processOptions (/Users/sinan/Documents/code/vue_projects/sinan/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/Users/sinan/Documents/code/vue_projects/sinan/node_modules/webpack/bin/webpack.js:397:2)
    at Object.Yargs.self.parse (/Users/sinan/Documents/code/vue_projects/sinan/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/sinan/Documents/code/vue_projects/sinan/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
